version: '3.8'

services: 
  web:
    container_name: vue_web
    build: ./docker/web
    ports: 
      - 8989:8989
    privileged: true
    volumes: 
      - ./server:/app/:cached
    tty: true
    stdin_open: true
    command: /bin/sh
